server:
  port: 8000

jpa:
  show-sql: false
  hibernate:
    ddl-auto: create-drop
datasource:
  url: jdbc:h2:mem:smockindev
  driver-class-name: org.h2.Driver
  username: sa
  password:

logging:
  file: ${user.home}/.smockin/log/smockin.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: WARN
    com.smockin: WARN
    org.hibernate: WARN
    ROOT: WARN

smockin:
  ftp.root.dir: "${user.home}/.smockin/ftp/"

auth.exclusions:
  /auth:
    - POST
  /user/mode:
    - GET
  /mockedserver/rest/status:
    - GET
  /mockedserver/jms/status:
    - GET
  /mockedserver/ftp/status:
    - GET
  /password/reset/token/*:
    - GET
    - POST

---
# NOTE
# The 'start.sh' script overrides the below DB related params using values defined
# in the DB config file: '$USER_HOME/.smockin/db/db.properties'.
spring:
  profiles:
    active: production
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    driver-class-name:
    username:
    password:
    maximumPoolSize: 10
    hikari:
      poolName: smockinpool
      idle-timeout: 10000
